package reporting

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/cutmob/argus/pkg/types"
)

// PDFExporter generates PDF inspection reports.
// For MVP, generates a structured text file. Swap in a real PDF library
// (e.g., go-pdf, gofpdf) for production.
type PDFExporter struct {
	outputDir string
}

func NewPDFExporter() *PDFExporter {
	dir := os.Getenv("ARGUS_REPORTS_DIR")
	if dir == "" {
		dir = "./reports"
	}
	os.MkdirAll(dir, 0755)
	return &PDFExporter{outputDir: dir}
}

func (e *PDFExporter) Name() string { return "pdf" }

func (e *PDFExporter) Export(report types.InspectionReport) error {
	filename := fmt.Sprintf("argus_report_%s_%s.txt",
		report.InspectionMode,
		time.Now().Format("20060102_150405"),
	)
	path := filepath.Join(e.outputDir, filename)

	var b strings.Builder

	b.WriteString("═══════════════════════════════════════════════\n")
	b.WriteString("               ARGUS INSPECTION REPORT         \n")
	b.WriteString("═══════════════════════════════════════════════\n\n")

	b.WriteString(fmt.Sprintf("Report ID:       %s\n", report.ID))
	b.WriteString(fmt.Sprintf("Session ID:      %s\n", report.SessionID))
	b.WriteString(fmt.Sprintf("Inspection Type: %s\n", report.InspectionMode))
	b.WriteString(fmt.Sprintf("Location:        %s\n", report.Location))
	b.WriteString(fmt.Sprintf("Inspector:       %s\n", report.Inspector))
	b.WriteString(fmt.Sprintf("Date:            %s\n", report.CreatedAt.Format("2006-01-02 15:04:05")))
	b.WriteString(fmt.Sprintf("Risk Level:      %s\n", report.RiskLevel))
	b.WriteString(fmt.Sprintf("Risk Score:      %.1f\n\n", report.RiskScore))

	b.WriteString("───────────────────────────────────────────────\n")
	b.WriteString("SUMMARY\n")
	b.WriteString("───────────────────────────────────────────────\n")
	b.WriteString(report.Summary + "\n\n")

	b.WriteString("───────────────────────────────────────────────\n")
	b.WriteString("DETECTED ISSUES\n")
	b.WriteString("───────────────────────────────────────────────\n\n")

	if len(report.Hazards) == 0 {
		b.WriteString("No issues detected.\n\n")
	} else {
		for i, h := range report.Hazards {
			b.WriteString(fmt.Sprintf("%d. %s\n", i+1, h.Description))
			b.WriteString(fmt.Sprintf("   Severity:   %s\n", h.Severity))
			b.WriteString(fmt.Sprintf("   Confidence: %.0f%%\n", h.Confidence*100))
			if h.RuleID != "" {
				b.WriteString(fmt.Sprintf("   Rule:       %s\n", h.RuleID))
			}
			b.WriteString("\n")
		}
	}

	b.WriteString("───────────────────────────────────────────────\n")
	b.WriteString("RECOMMENDATIONS\n")
	b.WriteString("───────────────────────────────────────────────\n\n")

	if len(report.Recommendations) == 0 {
		b.WriteString("No recommendations at this time.\n")
	} else {
		for i, rec := range report.Recommendations {
			b.WriteString(fmt.Sprintf("%d. %s\n", i+1, rec))
		}
	}

	b.WriteString("\n═══════════════════════════════════════════════\n")
	b.WriteString("Generated by ARGUS AI Inspection System\n")
	b.WriteString("═══════════════════════════════════════════════\n")

	if err := os.WriteFile(path, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("writing report: %w", err)
	}

	slog.Info("report exported as PDF", "path", path)
	return nil
}
