package reporting

import (
	"fmt"
	"html"
	"strings"

	"github.com/cutmob/argus/pkg/types"
)

func buildPlainTextReport(report types.InspectionReport) string {
	var b strings.Builder

	b.WriteString("ARGUS INSPECTION REPORT\n")
	b.WriteString("========================================\n\n")
	b.WriteString(fmt.Sprintf("Report ID:       %s\n", report.ID))
	b.WriteString(fmt.Sprintf("Session ID:      %s\n", report.SessionID))
	b.WriteString(fmt.Sprintf("Inspection Type: %s\n", report.InspectionMode))
	b.WriteString(fmt.Sprintf("Location:        %s\n", report.Location))
	b.WriteString(fmt.Sprintf("Inspector:       %s\n", report.Inspector))
	b.WriteString(fmt.Sprintf("Date:            %s\n", report.CreatedAt.Format("2006-01-02 15:04:05")))
	b.WriteString(fmt.Sprintf("Risk Level:      %s\n", report.RiskLevel))
	b.WriteString(fmt.Sprintf("Risk Score:      %.1f\n\n", report.RiskScore))

	b.WriteString("SUMMARY\n")
	b.WriteString("----------------------------------------\n")
	b.WriteString(report.Summary + "\n\n")

	b.WriteString("DETECTED ISSUES\n")
	b.WriteString("----------------------------------------\n")
	if len(report.Hazards) == 0 {
		b.WriteString("No issues detected.\n\n")
	} else {
		for i, h := range report.Hazards {
			b.WriteString(fmt.Sprintf("%d. %s\n", i+1, h.Description))
			b.WriteString(fmt.Sprintf("   Severity:   %s\n", h.Severity))
			b.WriteString(fmt.Sprintf("   Confidence: %.0f%%\n", h.Confidence*100))
			if h.RuleID != "" {
				b.WriteString(fmt.Sprintf("   Rule:       %s\n", h.RuleID))
			}
			if h.CameraID != "" {
				b.WriteString(fmt.Sprintf("   Camera:     %s\n", h.CameraID))
			}
			if !h.DetectedAt.IsZero() {
				b.WriteString(fmt.Sprintf("   Detected:   %s\n", h.DetectedAt.Format("2006-01-02 15:04:05")))
			}
			b.WriteString("\n")
		}
	}

	b.WriteString("RECOMMENDATIONS\n")
	b.WriteString("----------------------------------------\n")
	if len(report.Recommendations) == 0 {
		b.WriteString("No recommendations at this time.\n")
	} else {
		for i, rec := range report.Recommendations {
			b.WriteString(fmt.Sprintf("%d. %s\n", i+1, rec))
		}
	}

	b.WriteString("\nGenerated by ARGUS AI Inspection System\n")
	return b.String()
}

func buildHTMLReport(report types.InspectionReport) string {
	escape := html.EscapeString
	var b strings.Builder

	b.WriteString("<!doctype html><html><head><meta charset=\"utf-8\">")
	b.WriteString("<title>ARGUS Inspection Report</title>")
	b.WriteString("<style>")
	b.WriteString("body{font-family:Arial,sans-serif;max-width:900px;margin:32px auto;padding:0 16px;color:#1a1a1a;}")
	b.WriteString("h1{margin:0 0 8px;font-size:28px;} h2{margin-top:24px;font-size:18px;}")
	b.WriteString("table{border-collapse:collapse;width:100%;margin-top:8px;} th,td{border:1px solid #ddd;padding:8px;font-size:13px;text-align:left;}")
	b.WriteString(".meta p{margin:4px 0;} .muted{color:#666;} .badge{display:inline-block;padding:2px 8px;border-radius:10px;background:#f4f4f4;}")
	b.WriteString("ul{margin:8px 0 0 18px;} li{margin:6px 0;}")
	b.WriteString("</style></head><body>")

	b.WriteString("<h1>ARGUS Inspection Report</h1>")
	b.WriteString("<div class=\"meta\">")
	b.WriteString("<p><strong>Report ID:</strong> " + escape(report.ID) + "</p>")
	b.WriteString("<p><strong>Session ID:</strong> " + escape(report.SessionID) + "</p>")
	b.WriteString("<p><strong>Inspection Type:</strong> " + escape(report.InspectionMode) + "</p>")
	b.WriteString("<p><strong>Date:</strong> " + escape(report.CreatedAt.Format("2006-01-02 15:04:05")) + "</p>")
	b.WriteString("<p><strong>Risk:</strong> <span class=\"badge\">" + escape(string(report.RiskLevel)) + "</span> ")
	b.WriteString(fmt.Sprintf("<span class=\"muted\">(score %.1f)</span></p>", report.RiskScore))
	b.WriteString("</div>")

	b.WriteString("<h2>Summary</h2><p>" + escape(report.Summary) + "</p>")

	b.WriteString("<h2>Detected Issues</h2>")
	b.WriteString("<table><thead><tr><th>#</th><th>Description</th><th>Severity</th><th>Confidence</th><th>Rule</th><th>Camera</th><th>Timestamp</th></tr></thead><tbody>")
	if len(report.Hazards) == 0 {
		b.WriteString("<tr><td colspan=\"7\" class=\"muted\">No hazards detected.</td></tr>")
	} else {
		for i, h := range report.Hazards {
			b.WriteString("<tr>")
			b.WriteString(fmt.Sprintf("<td>%d</td>", i+1))
			b.WriteString("<td>" + escape(h.Description) + "</td>")
			b.WriteString("<td>" + escape(string(h.Severity)) + "</td>")
			b.WriteString(fmt.Sprintf("<td>%.0f%%</td>", h.Confidence*100))
			b.WriteString("<td>" + escape(h.RuleID) + "</td>")
			b.WriteString("<td>" + escape(h.CameraID) + "</td>")
			if h.DetectedAt.IsZero() {
				b.WriteString("<td></td>")
			} else {
				b.WriteString("<td>" + escape(h.DetectedAt.Format("2006-01-02 15:04:05")) + "</td>")
			}
			b.WriteString("</tr>")
		}
	}
	b.WriteString("</tbody></table>")

	b.WriteString("<h2>Recommendations</h2>")
	if len(report.Recommendations) == 0 {
		b.WriteString("<p class=\"muted\">No recommendations at this time.</p>")
	} else {
		b.WriteString("<ul>")
		for _, rec := range report.Recommendations {
			b.WriteString("<li>" + escape(rec) + "</li>")
		}
		b.WriteString("</ul>")
	}

	b.WriteString("<p class=\"muted\" style=\"margin-top:28px;\">Generated by ARGUS AI Inspection System</p>")
	b.WriteString("</body></html>")
	return b.String()
}
